import { StatsEnum } from "./pokemon-state";
import { TypesEnum } from "./pokemon-types";

export enum NaturesEnum {
  ADAMANT = 'ADAMANT',
  BASHFUL = 'BASHFUL',
  BOLD = 'BOLD',
  BRAVE = 'BRAVE',
  CALM = 'CALM',
  CAREFUL = 'CAREFUL',
  DOCILE = 'DOCILE',
  GENTLE = 'GENTLE',
  HARDY = 'HARDY',
  HASTY = 'HASTY',
  IMPISH = 'IMPISH',
  JOLLY = 'JOLLY',
  LAX = 'LAX',
  LONELY = 'LONELY',
  MILD = 'MILD',
  MODEST = 'MODEST',
  NAIVE = 'NAIVE',
  NAUGHTY = 'NAUGHTY',
  QUIET = 'QUIET',
  QUIRKY = 'QUIRKY',
  RASH = 'RASH',
  RELAXED = 'RELAXED',
  SASSY = 'SASSY',
  SERIOUS = 'SERIOUS',
  TIMID = 'TIMID',
}

export const PokemonNatures = [
  NaturesEnum.ADAMANT,
  NaturesEnum.BASHFUL,
  NaturesEnum.BOLD,
  NaturesEnum.BRAVE,
  NaturesEnum.CALM,
  NaturesEnum.CAREFUL,
  NaturesEnum.DOCILE,
  NaturesEnum.GENTLE,
  NaturesEnum.HARDY,
  NaturesEnum.HASTY,
  NaturesEnum.IMPISH,
  NaturesEnum.JOLLY,
  NaturesEnum.LAX,
  NaturesEnum.LONELY,
  NaturesEnum.MILD,
  NaturesEnum.MODEST,
  NaturesEnum.NAIVE,
  NaturesEnum.NAUGHTY,
  NaturesEnum.QUIET,
  NaturesEnum.QUIRKY,
  NaturesEnum.RASH,
  NaturesEnum.RELAXED,
  NaturesEnum.SASSY,
  NaturesEnum.SERIOUS,
  NaturesEnum.TIMID,
];

export interface NaturesDataInterface {
  increase: StatsEnum;
  decrease: StatsEnum;
}

export const NaturesData: { [key: string]: NaturesDataInterface } = {
  ADAMANT: { increase: StatsEnum.Atk,   decrease: StatsEnum.SpAtk },
  BASHFUL: { increase: StatsEnum.SpAtk, decrease: StatsEnum.SpAtk },
  BOLD:    { increase: StatsEnum.Def,   decrease: StatsEnum.Atk   },
  BRAVE:   { increase: StatsEnum.Atk,   decrease: StatsEnum.Spe   },
  CALM:    { increase: StatsEnum.SpDef, decrease: StatsEnum.Atk   },
  CAREFUL: { increase: StatsEnum.SpDef, decrease: StatsEnum.SpAtk },
  DOCILE:  { increase: StatsEnum.Def,   decrease: StatsEnum.Def   },
  GENTLE:  { increase: StatsEnum.SpDef, decrease: StatsEnum.Def   },
  HARDY:   { increase: StatsEnum.Atk,   decrease: StatsEnum.Atk   },
  HASTY:   { increase: StatsEnum.Atk,   decrease: StatsEnum.Atk   },
  IMPISH:  { increase: StatsEnum.Def,   decrease: StatsEnum.SpAtk },
  JOLLY:   { increase: StatsEnum.Spe,   decrease: StatsEnum.SpAtk },
  LAX:     { increase: StatsEnum.Def,   decrease: StatsEnum.SpDef },
  LONELY:  { increase: StatsEnum.Atk,   decrease: StatsEnum.Def   },
  MILD:    { increase: StatsEnum.SpAtk, decrease: StatsEnum.Def   },
  MODEST:  { increase: StatsEnum.SpAtk, decrease: StatsEnum.Atk   },
  NAIVE:   { increase: StatsEnum.Spe,   decrease: StatsEnum.SpDef },
  NAUGHTY: { increase: StatsEnum.Atk,   decrease: StatsEnum.SpDef },
  QUIET:   { increase: StatsEnum.SpAtk, decrease: StatsEnum.Spe   },
  QUIRKY:  { increase: StatsEnum.SpDef, decrease: StatsEnum.SpDef },
  RASH:    { increase: StatsEnum.SpAtk, decrease: StatsEnum.SpDef },
  RELAXED: { increase: StatsEnum.Def,   decrease: StatsEnum.Spe   },
  SASSY:   { increase: StatsEnum.SpDef, decrease: StatsEnum.Spe   },
  SERIOUS: { increase: StatsEnum.Spe,   decrease: StatsEnum.Spe   },
  TIMID:   { increase: StatsEnum.Spe,   decrease: StatsEnum.Atk   },
};